version: "1"

volumes:
  db-data:
    driver: local
  banking_kafka_data:
    driver: local
  zookeeper_data:
    driver: local
  redis-data:
    driver: local


services:
  db:
    image: postgres:15.1-alpine
    container_name: my_postgres_banking_db
    ports:
      - "5437:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    ports:
      - '9092:9092'
    volumes:
      - banking_kafka_data:/var/lib/kafka/data

  redis:
    image: redis:7.2-rc-alpine
    container_name: my_banking_redis
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data