version: "1"

volumes:
  db-data:
    driver: local


services:
  db:
    image: postgres:15.1-alpine
    container_name: my_postgres_banking_db
    ports:
      - "5437:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data